name: Build code, run unit test, run SCA using semgrep security scans for NodeJs App
on: push

jobs:
  semgrep:
    name: semgrep-oss/scan
    #needs: Snyk#
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')
    steps:
      # Fetch project source with GitHub Actions Checkout. Use either v3 or v4.
      - uses: actions/checkout@v4
      # Run the "semgrep scan" command on the command line of the docker image.
      - run: semgrep scan --config auto
